name: windows-release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --clean --noconfirm not_a_culture_fit.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NotACultureFitGUI
          path: dist/NotACultureFitGUI.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: NotACultureFitGUI
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: NotACultureFitGUI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
